net1Inhaltliche Gestaltung (Netto);unl1
net2Inhalt allgemein (Subnetto);unl1
n01zu oberflächliche / unkritische Themen                                                                  ;c=ca1'1'
n01zu subjektiv geschrieben                                                                                ;c=ca2'1'
n01zu viele verschiedene Themen                                                                            ;c=ca3'1'
n01zu wenig Versuchsanleitungen                                                                            ;c=ca4'1'
n01Themen nicht bedarfsorientiert / geringe Anwendungsansätze für Oberstufe                                ;c=ca5'1'
n01zu wenig didaktisch-methodische Anregungen                                                              ;c=ca6'1'
n01zu trocken / zu sachlich                                                                                ;c=ca7'1'
n01zu unwissenschaftlich / niedriges Niveau                                                                ;c=ca8'1'
n01kompliziert / schwer verständlich                                                                       ;c=ca9'1'
n01zu große Stofffülle / zu viele Informationen                                                            ;c=ca10'1'
n01zu kurze Artikel / längere Artikel sind besser                                                          ;c=ca11'1'
n01Themen sollten durchgehend geschrieben werden / Thema nicht erst auf späteren Seiten weiterführen       ;c=ca12'1'
n01Hefte zu dünn / zu wenig Inhalt                                                                         ;c=ca13'1'
n01englischer Titel gefällt nicht                                                                          ;c=ca14'1'
net2Spezifische Themeninhalte / Rubriken (Subnetto);unl1
n01nur biologische Themen / Ausrichtung                                                                    ;c=ca24'1'
n01Werbung / Werbeabsicht / Artikel als Werbemaßnahmen                                                     ;c=ca25'1'
n01zu wenig Arbeitsblätter/ zu wenig Kopiervorlagen                                                        ;c=ca26'1'
net1Optische Gestaltung (Netto);unl1
n01optische Aufmachung gefällt nicht                                                                       ;c=ca32'1'
n01zu unübersichtlich                                                                                      ;c=ca33'1'
n01zu wenig Tabellen / Graphiken                                                                           ;c=ca34'1'
n01zu wenig Bildmaterial / Fotos                                                                           ;c=ca35'1'
n01Schrift zu klein                                                                                        ;c=ca36'1'
net1Allgemeine Nennungen  (netto);unl1
n01erscheint zu selten                                                                                     ;c=ca44'1'
n01Artikel nicht einzeln entnehmbar / Seiten nicht perforiert                                              ;c=ca45'1'
n01keine kostenlosen Klassensätze                                                                          ;c=ca46'1'
n01Themenübersicht im Voraus oder rückblickend gewünscht                                                   ;c=ca47'1'
netend1
n01Sonstige                                                                                                ;c=ca98'1'
n01Weiß nicht/keine Angabe   ;c=-;nonz
